# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=fastapi_db
      - POSTGRES_PASSWORD=fastapi_db
      - POSTGRES_DB=fastapi_db
      - POSTGRES_PORT=5432
      - POSTGRES_MAX_CONNECTIONS=20
      - POSTGRES_MIN_CONNECTIONS=1
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_db
      - POSTGRES_PASSWORD=fastapi_db
      - POSTGRES_DB=fastapi_db
volumes:
  postgres_data:
