# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_db
      - POSTGRES_PASSWORD=fastapi_db
      - POSTGRES_DB=fastapi_db
volumes:
  postgres_data:
